name: co-many-world
version: 1.0
main: org.cakedek.comanyworld.CoManyWorld
description: A multi-world plugin for Minecraft 1.21.x
author: CakeDek [MC-OSOC]
commands:
  co-many:
    description: Commands for managing multiple worlds
    usage: /co-many <create|tp|list|del> [worldName] [worldType]
    permission: co.many.worlds.admin
permissions:
  co.many.worlds.admin:
    description: Allows admin to manage worlds
    default: op
  co.many.worlds.admindel:
    description: Allows admin to delete worlds
    default: op
